name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull LFS files
        run: git lfs pull

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Pushing to https://huggingface.co/spaces/ourl/livepotrait"
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config lfs.allowincompletepush true
          git push https://ourl:$HF_TOKEN@huggingface.co/spaces/ourl/livepotrait main
